---
name: pull_request
on: pull_request
jobs:
  foo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to federate tokens.
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: suzuki-shunsuke/example-octo-sts
          identity: pull_request
      - env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh repo list
      - env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
          NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh -R "$GITHUB_REPOSITORY" pr comment "$NUMBER" --body "Test Octo STS"
